version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - run: sudo apt-get update; sudo apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix do deps.get, compile
      - run: cd deps/libsecp256k1 && rebar compile

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run: elixir --erl "+hmax 33554432" -S mix test --exclude network
